import { defineConfig, devices } from "@playwright/test";

// E2E suite generated by the `generate-tests` subagent and executed by `healer`
// (see .claude/skills/verify-implementation). Unit tests stay in Vitest.
export default defineConfig({
  testDir: "./e2e",
  // The app has shared persisted state, so e2e specs run one at a time.
  fullyParallel: false,
  workers: 1,
  // A retry would mask a flaky app; the healer needs the raw first result.
  retries: 0,
  reporter: [["list"], ["json", { outputFile: "test-results/e2e-results.json" }]],
  use: {
    baseURL: "http://localhost:3000",
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
  webServer: {
    command: "npm run dev",
    url: "http://localhost:3000",
    reuseExistingServer: true,
    timeout: 120_000,
  },
});
